### ISSUE TITLE
Unable to use variables in appender AppName

### ISSUE THREAD

**Issue by sydah** [MarkZither/Log4net.Appender.InfluxDBSyslog#4]
Hi,

I'm unable to make use of variables in the InfluxAppender part. The goal would be to have my applications service name dynamically inserted in the AppName tag. At the moment it seems that variables do not get interpreted and therfore end up being pushed as a string.

I've tried multiple ways but I think the simplest way of demonstrating the issue would be this snippet:
``` 
<appender name="InfluxAppender" type="Log4net.Appender.InfluxDBSyslog.InfluxAppender, Log4net.Appender.InfluxDBSyslog">
        <Scheme>https</Scheme>
        <Host>influx.contoso.com</Host>
        <RemotePort>443</RemotePort>
        <AppName value="%date"></AppName>
        <Facility>Server</Facility>
</appender>
```

**Comment by MarkZither** [comment]
This can be tested now for AppName with the [0.3.0-alpha0001](https://www.nuget.org/packages/Log4net.Appender.InfluxDBSyslog/0.3.0-alpha0001) nuget package the syntax is as proposed
``` xml
<AppName>
    <layout type="log4net.Layout.PatternLayout">
	<conversionPattern value="%date Test Custom AppName" />
    </layout>
</AppName>
```
and the existing syntax still works and short circuits the layout
``` xml
<AppName>Test AppName</AppName>
```
